### ISSUE TITLE
1 down site results in no dashboard

### ISSUE THREAD

**Issue by jeffbryner** [mozilla/http-observatory-dashboard#1]
Just ran a make generate to get a refreshed dashboard and ran into this: 
`[centos@ip-172-31-35-19 httpobsdashboard]$ make generate
PYTHONPATH='..' python run.py json-generate

Unable to get result from the HTTP Observatory @ https://http-observatory.security.mozilla.org/api/v1/analyze?host=vreplay.mozilla.com. Error: site down.
make: **\* [json-generate] Error 1`

Sure enough, that host is down. I think the dashboard should still generate either skipping the host in question, or marking the host as down in the dashboard. Whatcha think?

**Comment by april** [comment]
I'll fix that today.  :)

**Comment by april** [comment]
Should be fixed in 505c80cfa9d0f87dce3db86e618cb39c32358be6.  Let me know if you run into errors like this again.

**Comment by jeffbryner** [comment]
Cool, thanks!
