### ISSUE TITLE
Suggested format change for sites.json

### ISSUE THREAD

**Issue by jonathanKingston** [mozilla/http-observatory-dashboard#10]
Currently sites.json has this format:
```
{
  "sites": {
    "Bug Bounty Sites": [],
    "ABSearch": [
      "search.services.mozilla.com"
    ],
   ...
```

This makes it somewhat painful in the template to support nesting `<div>` elements around the parent category names. It also means meta data to describe the category etc also isn't possible.

I'm proposing this format however not precious about it. Where the levels of categories could be N layers deep until it finds a "_sites" key and "_config" could be used at any level also.

```
{
  "Category name": {
    "Sub category": {
      "_sites": [
        "url", "url2"
      ]
    }
  }
}
```

What do you think @marumari

**Comment by april** [comment]
I was actually thinking

Tab Name -> Major Grouping -> Minor Group: [sites]

That way you could have, say, "Banking", "News", etc. across the top?

**Comment by jonathanKingston** [comment]
I was thinking of solving that with something like:
```
{
  "Category name": {
    "_metadata": {
     tabName: 'News',
     importance: 'high',
     somethingElse: 'thing'
   },
    "Sub category": {
      "_sites": [
```


Where the `<div` might end up like this:
```
<div data-tab-name="news" data-importance="high" data-something-else="thing">
```

I was thinking the tabbing could come from the group code itself where the grouping level could be n layers deep even (would have to work out how to template that though :D).

However I'm happy to bend to whatever format works best, I'm going to be maintaining a fairly large list and would like some meta data even for the url's themselves.

Some data I want to keep:
- Category
  - Country
  - Size
- Site
  - Country
  - BelongsToEntity
  - PrimarySite vs ProductSite

**Comment by april** [comment]
That works for me, if you want to make it so.  :)
