### ISSUE TITLE
Add additional sites to the Dashboard

### ISSUE THREAD

**Issue by april** [mozilla/http-observatory-dashboard#14]
The overview on https://riskheatmap.security.mozilla.org/observatory/ is missing:

# Engineering Productvity
https://treeherder.mozilla.org
https://bugherder.mozilla.org

# Release Engineering
https://api.pub.build.mozilla.org
https://secure.pub.build.mozilla.org
https://mozilla-releng.net

# Taskcluster
http://taskcluster.net
https://login.taskcluster.net
https://tools.taskcluster.net
https://docs.taskcluster.net

# Taskcluster APIs (not sure if these need to be added since API-only)
https://auth.taskcluster.net
https://aws-provisioner.taskcluster.net
https://cors-proxy.taskcluster.net
https://events.taskcluster.net
https://github.taskcluster.net
https://hooks.taskcluster.net
https://index.taskcluster.net
https://notify.taskcluster.net
https://public-artifacts.taskcluster.net
https://pulse.taskcluster.net
https://purge-cache.taskcluster.net
https://queue.taskcluster.net
https://scheduler.taskcluster.net
https://schemas.taskcluster.net
https://secrets.taskcluster.net

# Other
https://mozilla.okta.com
https://mozilla.service-now.com
https://mana.mozilla.org
https://pto.mozilla.org
https://public.etherpad-mozilla.org
https://pastebin.mozilla.org
https://hacks.mozilla.org

**Comment by edmorley** [comment]
Many thanks for moving this over :-)

**Comment by floatingatoll** [comment]
old.etherpad-mozilla.org should go alongside public. It seems like a
redirect, but it's actually a functional site of its own, if you have the
right inbound URL.

**Comment by edmorley** [comment]
Many thanks!
