### ISSUE TITLE
Add a source/file bug link

### ISSUE THREAD

**Issue by edmorley** [mozilla/http-observatory-dashboard#15]
Since the Observatory dashboard is hosted on https://riskheatmap.security.mozilla.org I didn't realise it had it's own repo when filing bug 1338157 / bug 1338178.

I'm not sure if bug 1338157 will just add source links for the main heatmap parts or for the observatory dashboard too, so filing this in case it doesn't link here :-)

**Comment by april** [comment]
Yeah, the riskheatmap stuff is on Bugzilla, since jeff maintains it.  The iframe that contains the dashboard information is here.  Sorry, I know that's really confusing!
