### ISSUE TITLE
Change bug bounty sites to conform to Bug Bounty relaunch

### ISSUE THREAD

**Issue by tristanweir** [mozilla/http-observatory-dashboard#16]
Sync Bug Bounty sites in https://github.com/mozilla/http-observatory-dashboard/blob/master/httpobsdashboard/conf/sites.json

using sites updated 

https://github.com/mozilla/bedrock/pull/4777

@fox2mike for awareness

**Comment by april** [comment]
I'll do this as soon as the relaunch goes live, hopefully this week. I can push an update to the dashboard a lot faster than I can push an update to bedrock.

**Comment by tristanweir** [comment]
@fox2mike and I are going to do some regrouping on sites on Friday so we can update this then or if you have a chance to get to it beforehand, that would be great.

**Comment by april** [comment]
Oh sure, I can take care of this tomorrow.  Thanks for reminding me!

**Comment by floatingatoll** [comment]
@tristanweir For the record, does a47a9ec contain the output of your meeting with Shyam on the Friday following May 9th?
