### ISSUE TITLE
90 day trend issue

### ISSUE THREAD

**Issue by jeffbryner** [mozilla/http-observatory-dashboard#18]
In 
<img width="894" alt="screen shot 2017-07-18 at 4 07 25 pm" src="https://user-images.githubusercontent.com/566889/28372597-fe45fe9a-6c54-11e7-8c99-cf9d5b07d31e.png">
you can see the dashboard reporting a 90 day trend of 0 even though the improvement in the score happened within the last 90 days as seen in 
<img width="1074" alt="screen shot 2017-07-18 at 4 09 15 pm" src="https://user-images.githubusercontent.com/566889/28372636-22591fb0-6c55-11e7-9803-748d2fd52c86.png">

**Comment by floatingatoll** [comment]
October 16th was 90 days ago.
